# Generated by Django 5.1.2 on 2024-10-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0004_alter_role_can_assign_tasks_alter_role_can_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooluser',
            name='name',
            field=models.TextField(default='ruby'),
            preserve_default=False,
        ),
    ]
