# Generated by Django 5.1.2 on 2024-10-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0005_tooluser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='To Do', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
