# Generated by Django 5.1.2 on 2024-10-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0006_alter_task_due_date_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reporter_id_fk',
            new_name='Assigned by',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_user_id_fk',
            new_name='Assigned to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id_fk',
            new_name='Project',
        ),
    ]
