# Generated by Django 5.1.2 on 2024-10-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0011_remove_task_assigned_to_remove_task_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_create_task', 'Can create task'), ('can_delete_task', 'Can delete task'), ('can_update_task', 'Can update task')]},
        ),
    ]
