# Generated by Django 5.1.2 on 2024-10-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0012_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
